status = "systemctl status" #deixar 4 primeiras linhas
start = ""
stop = "shutdown -h now"
sleep = "sleep 30"
restart = "reboot"
hostname = "hostname"
ip = "hostname --ip-address"
disk_space = "df -m | grep user | grep -o '[0-9]*' | awk 'NR==4'"
cpu_number = "lscpu | grep 'CPU(s):' | awk '{print $2}'"
cpu_model = "lscpu | grep '^Nome do modelo:' "
ram = "free -m | grep Mem | awk '{print $2;}'"
linux_version = "cat /etc/fedora-release"
#java_version = "java -version | grep -o 'java version' | awk '{print$3}'"
java_version = "java -version"    